Kesin11/CIAnalyzer

- __tests__/config/circleci_config.test.ts
- __tests__/config/github_config.test.ts
- __tests__/config/jenkins_config.test.ts
- __tests__/exporter/local_exporter.test.ts
- __tests__/store/local_store.test.ts
- src/config/config.ts
- src/exporter/exporter.ts
- src/exporter/local_exporter.ts
- src/last_run_store.ts
- src/runner/circleci_runner.ts
- src/runner/github_runner.ts
- src/runner/jenkins_runner.ts
- src/store/local_store.ts
Previously LastRunStore `local` backend and `LocalExporter` output path are resolved from current directory.
Now both output path are resolved from config file directory.
If you exec with `ts-node src/index.ts -c sample/ci_analyzer.yaml`, output files will be created in `sample` directory.
> BREAKING CHANGES: Output path will be resolved from config directory.

- __tests__/client/circleci_client.test.ts
- __tests__/client/github_client.test.ts
- __tests__/client/jenkins_client.test.ts
- src/client/circleci_client.ts
- src/client/github_client.ts
- src/client/jenkins_client.ts
- src/runner/circleci_runner.ts
- src/runner/github_runner.ts
- src/runner/jenkins_runner.ts
Bugfix some case in_progress job never export.
```
build_id: 2, status: finished
build_id: 3, status: in_progress
build_id: 4, status: finished
```
Above case exports `build_id: 2,4` and LastRunId will be detect 4 and store it. Next time fetch runs will start from `build_id: 5`. It means `build_id: 3` never export.
This PR resolve this issue. In above case, exports only `build_id: 2` and ignore `build_id: 3, 4`. Next time fetch runs will start from `build_id: 3`.
> Filter runs that after in_progress run

- __tests__/client/circleci_client.test.ts
- __tests__/client/github_client.test.ts
- __tests__/client/jenkins_client.test.ts
- src/client/circleci_client.ts
- src/client/github_client.ts
- src/client/jenkins_client.ts
Fix bug created by #13
- Jenkins `NOT_EXECUTED` status is not mean 'in progress'
- Filter after in_progress run algorithm is incorrect. When there are multiple in_progress runs.
- See fixed test case.
> fix: Bugfix how to detect in_progress run

- bigquery_schema/workflow_report.json
- src/analyzer/analyzer.ts
- src/analyzer/circleci_analyzer.ts
- src/analyzer/github_analyzer.ts
- src/analyzer/jenkins_analyzer.ts
- src/client/jenkins_client.ts
- src/store/gcs_store.ts
- src/store/local_store.ts
Output Jenkins build parameters.
If parameters types are boolean or number or others, these convert to string types.
However CircleCI and GithubActions also have build parameters, currently only support Jenkins.
> Add Jenkins job parameter to workflow report

- Dockerfile
- sample/cron.jenkinsfile
- src/index.ts
Previously, we have to mount each file or directory that will be load or create by CIAnalyzer.
Previous `docker run` options are Like this.
```
--mount type=bind,src=${CONFIG_FILE_PATH},dst=/app/ci_analyzer.yaml \
--mount type=bind,src=${WORKSPACE}/output,dst=/app/output \
--mount type=bind,src=${WORKSPACE}/.ci_analyzer,dst=/app/.ci_analyzer \
--mount type=bind,src=${SERVICE_ACCOUNT},dst=/app/service_account.json \
```
This pull-req reduce mount file or directory that need for CIAanalyzer. We will need just only mount current directory (pwd) to `/app`.
> Improve docker run command with volume mount

- package-lock.json
- package.json
When run using docker image, it could not import `minimatch`.
I forgot to install `minimatch` as production dependency.
```
internal/modules/cjs/loader.js:969
throw err;
^
Error: Cannot find module 'minimatch'
```
> bugfix: Install minimatch

- src/analyzer/circleci_analyzer.ts
- src/client/circleci_client.ts
Sometimes CircleCI API returns a response that has invalid step data.
Invalid step is like this
```
actions: [{
"status": "running",
"end_time": null,
"run_time_millis": null
}] 
```
even build lifecycle is "finished".
If CircleciAnalyzer makes report from a build that includes invalid step, `completedAt` will be translated 1970-01-01. As a result, stepDurationSec will be a very large minus value (around -1.59E9).
> fix: Validate CircleCI step end_time

- package-lock.json
- package.json
- src/analyzer/github_analyzer.ts
- src/analyzer/jenkins_analyzer.ts
Some language ecosystem test report using `<testsuite></testsuite>` as root tag for JUnit XML. (e.g. Android test report)
If CIAnalyzer collects this type of JUnit XML, it's complete some properties and create test reports as same as `<testsuites></testsuites>` root tag XML.
> Support creating test report from testsuite tag root XML

- __tests__/exporter/bigquery_exporter.test.ts
- __tests__/exporter/local_exporter.test.ts
- ci_analyzer.yaml
- jest.config.js
- src/config/config.ts
- src/exporter/bigquery_exporter.ts
- src/exporter/exporter.ts
- src/exporter/local_exporter.ts
CIAnalyzer support loading TestReport to BigQuery now.
**BREAKING CHANGES**: Change config file exporter.bigquery schama.
`exporter.bigquery.table` is deprecated. Please fix to `exporter.bigquery.reports`.
```yaml
bigquery:
project: GCP_PROJECT
dataset: BIGQUERY_DATASET
reports:
- name: workflow
table: WORKFLOW_TABLE
- name: test_report
table: TESTREPORT_TABLE
```
> BigqueryExporter support loading TestReport

- src/config/config.ts
- src/exporter/exporter.ts
Fix bug that throw exception when exporter.local is null.
> fix: Set default param when exporter.local is null

- package-lock.json
- package.json
- src/analyzer/github_analyzer.ts
- src/client/github_client.ts
fix: #67
Bump @octokit/rest to v18 and fix deprecated method.
See more detail about v18 changes: https://github.com/octokit/rest.js/releases/tag/v18.0.0
> Bump @octokit/rest to v18

- Jenkinsfile
- Revert parallel run. On my machine, the execution time has been increased by parallel run.
- Skip lint stage. `npm run lint` has not been implemented yet but lint stage waste of time with `npm ci`.
> Improve Jenkins CI again

- Jenkinsfile
Sometimes Jenkins job never finish in my machine.
Change `timeout` place entire options to steps to check timeout more strictly.
> ci: Fix Jenkinsfile timeout more strictly

- src/custom_report_collection.ts
- src/index.ts
- src/result.ts
- src/runner/circleci_runner.ts
- src/runner/github_runner.ts
- src/runner/jenkins_runner.ts
- src/runner/runner.ts
- tsconfig.json
BREAKING CHANGE
Formerly, CIAnalyzer returns 0 despite of some runner throws error.
In this case, CIAnalyzer returns error code 1 now. 
`Promise.all()` abort all parallel execution immediately when one of promise is rejected.
While `Promise.allSettled()` does not abort in this case, so it more suitable for parallel execution.
> Improve some features about parallel execution

- sample/cron.jenkinsfile
The latest version of Jenkins alert me sample code of Jenkinsfile has insecure interpolation of sensitive variables.
https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#string-interpolation
> chore: Fix insecure interpolatoin code in sample Jenkinsfile

- bigquery_schema/workflow_report.json
- src/analyzer/analyzer.ts
- src/analyzer/circleci_analyzer.ts
- src/analyzer/github_analyzer.ts
- src/analyzer/jenkins_analyzer.ts
- src/client/jenkins_client.ts
- src/exporter/bigquery_exporter.ts
Correct queuedDurationSec that duration time in build queue and export it.
Jenkins needs to install [Metrics plugin](https://plugins.jenkins.io/metrics/) to correct queued time data.
> feat: Export queuedDurationSec

- src/client/jenkins_client.ts
Previously, CIAnalyzer throw errors when collecting job that name includes multibyte string.
This pull request fixes that bug.
> fix(Jenkins): Bugfix to allow multibyte Jenkins job name

- src/analyzer/circleci_analyzer.ts
- src/client/circleci_client.ts
Some CircleCI steps running background and these step times are almost the same as job duration.
e.g. https://circleci.com/docs/2.0/databases/
Background steps are not related to the critical path of workflow so it should be ignored.
> fix(CircleCI): Ignore background step

- src/runner/jenkins_runner.ts
- src/runner/runner.ts
CIAnalyzer throws an error and stopping run when using `correctAllJobs` and your Jenkins has some jobs that has not any build histories.
`job/JOB_NAME/lastBuild/json` API returns 404 when the job has not any build histories.
> fix: Skip fetch Jenkins job that has not any build

- .github/workflows/shipjs-trigger.yml
This is a workaround for an issue that workflow can not trigger another one.
see:
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148/4
> ci: Enable to trigger push tag event for build Docker

- src/analyzer/circleci_analyzer.ts
Formerly, CircleCI workflowDurationSec is just the sum of steps time. It differs from other services time that calcurated by `workflow's completedAt - workflow's startedAt`.
So this pull-req fixes CircleCI workflowDurationSec formula to match others.
> fix(CircleCI): Fix workflowDurationSec correctly when jobs ran in parallel.

- .github/workflows/docker.yml
see: https://github.blog/changelog/2021-03-24-packages-container-registry-now-supports-github_token/
> ci: Using GITHUB_TOKEN to push ghcr.io instead of PAT

- .github/workflows/docker.yml
ref: https://github.com/Kesin11/CIAnalyzer/pull/253
Migrate ghaction-docer-meta v1 to v2. See: https://github.com/crazy-max/ghaction-docker-meta/blob/master/UPGRADE.md
> Migrate craze-max/ghaction-docker-meta@2

- ci_analyzer.yaml
- src/client/bitrise_client.ts
ref: https://api-docs.bitrise.io/
/apps/{app-slug}/builds
> limit integer(query) | Max number of build artifacts per page is 50.
The document does not say max number of limit, but they return an error when request `limit: 100`.
> Fix Bitrise API max limit number

- __tests__/config/circleci_config.test.ts
- ci_analyzer.yaml
- sample/ci_analyzer_circleci.yaml
- src/config/circleci_config.ts
- src/config/config.ts
- src/runner/circleci_runner.ts
- src/runner/github_runner.ts
BREAKING CHANGES
Fix typo key in CIAnalyzer config yaml.
- `vsc_type` -> `vcs_type`
- `vscBaseUrl` -> `vcsBaseUrl`
So please fix key name in config yaml if you use these keys.
> Fix config key typo vsc -> vcs

- __tests__/client/circleci_client.test.ts
- src/client/circleci_client.ts
CircleCI finished workflow filter try to export only that workflows:
`last run build number < Want to export workflow build numbers < First inprogress build number`
It treats `lifecycle !== finished` workflow as 'in progress' workflow. But `not_run` lifecycle workflows that are [ci-skip] commit  or skipped redundant build also treated as 'in progress'.
That is serious mistake so I fix this filter condition, and increase fetch workflow number for the project that build history has many `not_run` build.
> Fix finished workflow filter does not work properly in CircleCI

- README.md
- __tests__/client/circleci_client.test.ts
- __tests__/client/circleci_client_v2.test.ts
- __tests__/config/circleci_config.test.ts
- __tests__/config/jenkins_config.test.ts
- __tests__/last_run_store.test.ts
- __tests__/runner/circleci_runner_v1.test.ts
- __tests__/runner/circleci_runner_v2.test.ts
- ci_analyzer.yaml
- sample/ci_analyzer_circleci.yaml
- src/analyzer/circleci_analyzer_v2.ts
- src/client/circleci_client.ts
- src/client/circleci_client_v2.ts
- src/config/bitrise_config.ts
- src/config/circleci_config.ts
- src/config/github_config.ts
- src/config/jenkins_config.ts
- src/last_run_store.ts
- src/runner/circleci_runner.ts
- src/runner/circleci_runner_v1.ts
- src/runner/circleci_runner_v2.ts
Support CircleCI API v2 🎉 
So CircleCI v1.1 does not provide API that about pipeline, previously CIAnalyzer reconstruct pipeline structure from each job.
Now, CIAnalyzer uses a pipeline data structure provided by API v2. The exported data will be closer to what you can see on the CircleCI website. 
After upgrade CIAnalzyer version newer than v4.2, do not need any changes in your config YAML if you want to still use CircleCI API v1.1 .
When you want to use CircleCI v2, you have to change the config as below.
```yaml
baseUrl: https://circleci.com/api/v1.1
baseUrl: https://circleci.com/api/ # Remove suffix "v1.1" from URL
version: 2 # Add
```
**NOTICE** The first time after you enable v2, CIAnalyzer reset the LastRun build number and will export the last 100 pipeline data. As a result, it …
> Support using CircleCI API v2

- package-lock.json
- package.json
Some Dependabot alerts come from shipjs dependencies.
However, shipjs is a just `devDependencies` and it is used for just release workflow. So to prevent alerts that unrelated in future, remove shipjs from package.json and use from `npx`.
> Remove shipjs from package.json

- __tests__/client/jenkins_client.test.ts
- package-lock.json
- package.json
- src/@types/axios-concurrency.ts
- src/arg_options.ts
- src/client/bitrise_client.ts
- src/client/circleci_client.ts
- src/client/circleci_client_v2.ts
- src/client/client.ts
- src/client/jenkins_client.ts
- src/index.ts
- src/runner/jenkins_runner.ts
- tsconfig.json
I found CIAnalyzer sometimes creates too many request connections and these may reject by the network layer. I faced this problem in my Jenkins that using GCP Cloud NAT.
Some methods create requests concurrently. If using `correctAllJobs` option in Jenkins config, concurrent request number is reached same as **registered job number in Jenkins**. 
**BREAKING CHANGES**
To handle this problem, use keepalive and limit the number of concurrent requests. Both behaviors are set in default, but these can disable through `--keepalive` and `--max-concurrent-requests`.
> Limit request concurrency

- src/client/client.ts
Sometimes error log has not any data about request. I faced it request timeout error. 
Axios error object has data about requests even if the server does not respond with any data.
> fix: Show request info when timeout error

- src/client/jenkins_client.ts
- src/runner/jenkins_runner.ts
Handle these Jenkins API error responses and just skip that jobs to prevent CIAnalzer exit code 0
- `job/$jobName/lastBuild/api/json`
- `job/$jobName/wfapi/runs`
> Fix Jenkins API error response handling

- src/analyzer/bitrise_analyzer.ts
- src/client/bitrise_client.ts
fix #518 
CIAnalyzer can fetch builds that have not build log and won't be stopped by build log API 404 response now.
As mentioned by @takeya0x86 If you enable Bitrise rolling build config and when queued builds are aborted by rolling build, these have no build log and API response 404.
> fix(Bitrise): Handle error build that aborted rolling build

- .circleci/config.yml
- .earthignore
- Earthfile
- package.json
- proto/Earthfile
- Specify `VERSION` in Earthfile
- More strict COPY to avoid cache busting
- ~~Use experiment `CACHE` command for npm cache~~
- More quietly build log
- Enable `protoc` build stage cache
> Improve earthly build

- jest.config.js
see: https://kulshekhar.github.io/ts-jest/docs/getting-started/options/isolatedModules
It makes faster about 2-3x at my Codespace and 1.6x at Github Actions.
before: https://github.com/Kesin11/CIAnalyzer/runs/6973028988?check_suite_focus=true
> Test Suites: 19 passed, 19 total
> Tests:       128 passed, 128 total
> Snapshots:   0 total
> Time:        12.152 s
after: https://github.com/Kesin11/CIAnalyzer/runs/6981208435?check_suite_focus=true
> Test Suites: 19 passed, 19 total
> Tests:       128 passed, 128 total
> Snapshots:   0 total
> Time:        7.505 s
> Ran all test suites.
> chore: Improve jest test time with isolateModules option

- sample/circleci_cron.yml
CIAnalyzer is alpine based image and it has
only packages to work Node.js
Even if CIAnalyzer works fine at CircleCI but they recommend to install some packages manually.
> doc(CircleCI): Add alpine based image workaround

- package-lock.json
- package.json
- src/client/bitrise_client.ts
- src/client/circleci_client.ts
- src/client/circleci_client_v2.ts
- src/client/github_client.ts
- src/client/jenkins_client.ts
- src/runner/runner.ts
- src/store/null_store.ts
- tsconfig.json
Require nodejs >= 16 to enable `target: ES2022` that need if using newer nodejs features.
First of all, replace TypeScript `private` to nodejs private field.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields
> Enable ES2022 feature

- .github/workflows/docker.yml
- Earthfile
Previously, use akhilerm/tag-push-action for pushing versioned image tags(e.g. v5, v5.0, v5.0.0),
Earthly can push multiple tags directly using new `FOR` syntax from v0.6. So it will no need to push `ghcr.io/kesin11/ci_analyzer_earthly`  and using tag-push-action.
> Push release image tags from Earthly

- jest.config.js
ts-jest v29 deprecate to set options in `globals` and change to use `transform`. This change also affected `ts-jest` preset.
https://github.com/kulshekhar/ts-jest/pull/3780
As a result, `isolatedModules` that set in `globals` is ignored and the test run time has increased compared to v28.
[It seems possible to set `isolatedModules` option with preset](https://kulshekhar.github.io/ts-jest/docs/getting-started/presets), but it is more complicated than with `globals` in v28. So I config `transform` manually instead of using  `preset: 'ts-jest'`.
> chore(ci): Re enable ts-jest isolatedModules option

- __tests__/client/github_client.test.ts
- src/client/github_client.ts
Previously, GitHub Actions run data that still `queued` status were collected accidentaly.
Collected data were invalid because CIAnalyzer expect fetched run data status are "completed".
To fix it, filter accept status only "completed".
> fix(Github): Bugfix Collecting invalid run data when some job are queued

- .github/workflows/ci.yml
- .github/workflows/docker.yml
If use earthly/actions-setup@v1 reported these warning. Current v1.0.2 uses node16 so we pinned that version.
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: earthly/actions-setup@v1
```
> chore(ci): Bump earthly/actions-setup

- __tests__/client/circleci_client.test.ts
- __tests__/client/circleci_client_v2.test.ts
- __tests__/client/jenkins_client.test.ts
- __tests__/exporter/bigquery_exporter.test.ts
- __tests__/exporter/local_exporter.test.ts
- __tests__/runner/circleci_runner_v1.test.ts
- __tests__/runner/circleci_runner_v2.test.ts
- __tests__/store/local_store.test.ts
- __tests__/store/null_store.test.ts
- src/index.ts
ref: https://github.com/Kesin11/CIAnalyzer/pull/699
I found part of log string that tslog `name` property does not shown at black background terminal, so back to white.
And migrate tslog config in test code.
> Fix tslog style

- package-lock.json
- package.json
Degraded by https://github.com/Kesin11/CIAnalyzer/pull/891
```
$ docker run ghcr.io/kesin11/ci_analyzer:master
node:internal/modules/cjs/loader:1078
throw err;
^
Error: Cannot find module 'zod-to-json-schema'
Require stack:
- /ci_analyzer/dist/config/config.js
- /ci_analyzer/dist/index.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
at Module._load (node:internal/modules/cjs/loader:920:27)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/ci_analyzer/dist/config/config.js:10:46)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at …
```
> bugfix move zod-to-json-schemato prod module

- __tests__/client/github_client.test.ts
- src/client/github_client.ts
When repository enables CodeQL default workflow, sometimes CIAnalyzer throws an error and could not complete.
To handle this issue easily, CIAnalyzer will only handle user generated workflows that paths are `.github/workflows/*`.
> Bugfix ignore auto generated workflow(e.g. CodeQL)

- sample/README.md
- sample/github_cron.yml
Update GitHub Actions sample using OIDC instead of service account secrets.
See also:
- https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
- https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform
> chore(docs): Update GitHub Actions sample using OIDC

- src/constant.ts
- src/exporter/bigquery_exporter.ts
We introduced esbuild at https://github.com/Kesin11/CIAnalyzer/pull/1041, however BigQueryExporter does not work.
> bugfix: BigQueryExporter does not work with esbuild

- src/client/circleci_client_v2.ts
fix: https://github.com/Kesin11/CIAnalyzer/issues/1120
CircleCI [job detail API](https://circleci.com/docs/api/v2/index.html#operation/getJobDetails) will fail with 404 when trying to fetch an approval job.
Previously CIAnalyzer would throw an error and stop when fetching this type of job. This PR fixes this problem by ignoring the approval job.
```bash
$ curl -sS -u "$CIRCLECI_TOKEN:" https://circleci.com/api/v2/workflow/e3beb02d-56b1-4756-8c4b-3e1142abf0f9/job
{
"next_page_token" : null,
"items" : [ {
"dependencies" : [ ],
"job_number" : 11256,
"id" : "49edd5ca-f340-46fa-9457-7b3621f3bb3a",
"started_at" : "2024-03-11T14:56:45Z",
"name" : "lint",
"project_slug" : "gh/Kesin11/CIAnalyzer",
"status" : "success",
"type" : "build",
"stopped_at" : "2024-03-11T14:56:59Z"
}, {
"dependencies" : [ …
```
> Bugfix CircleCI v2 throw error when fetching approval job

- biome.jsonc
package.json is rewritten by 'npm version', so it conficts with biome formatter.
> Biome formatter ignore package.json

- src/client/github_client.ts
Hi, Kesin11. I think CIAnalyzer is great tool and want use it in my work.
Firstly I appreciate that you make it!!
- We use Monorepo. Therefore many workflows exist.
- set per_page 100 for GitHub fetchWorkflows
- Number of per_page is 30 default. Sometimes big repository has more workflows.
> set per_page 100 for GitHub fetchWorkflows

- bigquery_schema/workflow_report.json
- proto/workflow.proto
- src/analyzer/bitrise_analyzer.ts
- src/analyzer/circleci_analyzer.ts
- src/analyzer/circleci_analyzer_v2.ts
- src/analyzer/github_analyzer.ts
- src/analyzer/jenkins_analyzer.ts
- src/pb_types/workflow.ts
fix: https://github.com/Kesin11/CIAnalyzer/issues/1302
Currently it only implemented GitHub Actions. Other services fill dummy value '0'.
BigQuery table schema will migrate automatically so it does not have breakings changes. (=minor update)
> Add `queuedDurationSec` for job

- README.md
- __tests__/exporter/bigquery_exporter.test.ts
- __tests__/exporter/gcs_exporter.test.ts
- __tests__/exporter/local_exporter.test.ts
- ci_analyzer.yaml
- package.json
- schema.json
- src/config/schema.ts
- src/exporter/exporter.ts
- src/exporter/gcs_exporter.ts
- src/exporter/local_exporter.ts
Add `exporter.gcs` config that allows CIAnalyzer export JSONL files to GCS.
BigQuery can also read JSONL formatted data stored in GCS as [external tables](https://cloud.google.com/bigquery/docs/external-data-cloud-storage), so it is useful to save data to GCS instead of exporting directly to a BigQuery table.
----
Initial [Copilot Workspace Session](https://copilot-workspace.githubnext.com/Kesin11/CIAnalyzer?shareId=cd1138d7-8fd9-4811-a19b-cb78c8722d5f)
> Add GcsExporter

- .github/workflows/ci.yml
- .github/workflows/docker.yml
- .github/workflows/release.yml
Pin specific commit hashes for third-party actions and explicitly define permissions for workflows to enhance security and control.
> Pin action versions and add permissions to workflows

- package-lock.json
- package.json
This pull request addresses a potential issue introduced by #1430, which may have caused the BigQuery exporter to break. It appears that the version of gaxios has changed, leading to this problem.
Error log in my testing workflow that uses CIAnalyzer master branch. It seems gaxios related this error.
```
node:internal/process/promises:394
triggerUncaughtException(err, true /* fromPromise */);
^
_GaxiosError: Expected signal to be an instanceof AbortSignal
at Gaxios._request (file:///ci_analyzer/dist/index.mjs:15543:65)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async IdentityPoolClient.requestAsync (file:///ci_analyzer/dist/index.mjs:21392:22)
at async Upload.makeRequestStream (file:///ci_analyzer/dist/index.mjs:86401:17)
at async …
```
> Revert @google-cloud/common v6 to v5.0.2

- .github/workflows/ci.yml
- package-lock.json
- package.json
revert #1494 
dist js bundled by esbuild broken from yargs v18
```
$ node dist/index.mjs
file:///home/kesin/github/kesin11/CIAnalyzer/dist/index.mjs:50483
import { createRequire } from "node:module";
^^^^^^^^^^^^^
SyntaxError: Identifier 'createRequire' has already been declared
at compileSourceTextModule (node:internal/modules/esm/utils:344:16)
at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:105:18)
at #translate (node:internal/modules/esm/loader:534:12)
at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:581:27)
at async ModuleJob._link (node:internal/modules/esm/module_job:116:19)
Node.js v22.16.0
```
I also added a smoke test to prevent dependency package issues like this from happening again in the future.
> revert yargs v18
