Kesin11/CIAnalyzer

ci_analyzer.yaml
src/analyzer/circleci_analyzer.ts
src/client/circleci_client.ts
src/client/github_client.ts
src/client/jenkins_client.ts
src/config/circleci_config.ts
src/config/config.ts
src/config/github_config.ts
src/config/jenkins_config.ts
src/exporter/exporter.ts
src/last_run_store.ts
src/runner/circleci_runner.ts
src/runner/github_runner.ts
src/runner/jenkins_runner.ts

- Save last run id after success export
- Load lat run id before execute next time
- Filter runs that already exported last execute time

Save last run id and output only newer run at next time.

---

.circleci/config.yml
.github/workflows/ci.yml
.github/workflows/docker.yml
Jenkinsfile

Fix each CI service's pipeline to improve build time.
We can validate these changes are improving build speed or not seeing dashboard made by CIAnalyzer.

Improve CI build time

---

.github/workflows/ci.yml
.github/workflows/docker.yml

Published!
https://github.com/Kesin11/CIAnalyzer/packages/214494

docker push to github package registry

---

bigquery_schema/workflow_report.json
src/analyzer/analyzer.ts
src/analyzer/circleci_analyzer.ts
src/analyzer/github_analyzer.ts
src/analyzer/jenkins_analyzer.ts
src/client/github_repository_client.ts
src/config/config.ts
src/runner/circleci_runner.ts
src/runner/github_runner.ts

Add tag data into workflow report if a build headSha links some git tag.

Add tag data into workflow report

---

.github/workflows/ci.yml
package-lock.json
package.json

Collect test coverage using Codecov.

test: Add codecov to collect coverage

---

README.md
__tests__/last_run_store.test.ts
__tests__/store/local_store.test.ts
ci_analyzer.yaml
codecov.yml
package-lock.json
package.json
src/config/config.ts
src/last_run_store.ts
src/runner/circleci_runner.ts
src/runner/github_runner.ts
src/runner/jenkins_runner.ts
src/store/gcs_store.ts
src/store/local_store.ts
src/store/store.ts

BREAKING CHANGES config schema `lastRunStore`
We can choose backend that is how to and where to save LastRunStore.
Currently local filesystem and GCS are supported.

Read/Write LastRunStore to GCS

---

.github/workflows/shipjs-trigger.yml
package-lock.json
package.json
ship.config.js

Add shipjs to automate release flow.
CIAnalyzer doesn't need to publish to npm but need to create Github Releases.
So I disable shipjs release to npm flow.

Add shipjs

---

.circleci/config.yml
.github/workflows/ci.yml
.gitignore
Jenkinsfile
jest.config.js
package-lock.json
package.json

Store CIAnalyzer test result on each CI service. It is prepare step for implement next CIAnalyzer feature.

Store own test result

---

__tests__/config/github_config.test.ts
__tests__/config/jenkins_config.test.ts
package-lock.json
package.json
src/analyzer/analyzer.ts
src/analyzer/circleci_analyzer.ts
src/analyzer/github_analyzer.ts
src/analyzer/jenkins_analyzer.ts
src/artifact_extractor.ts
src/client/circleci_client.ts
src/client/github_client.ts
src/client/jenkins_client.ts
src/config/config.ts
src/config/github_config.ts
src/config/jenkins_config.ts
src/exporter/bigquery_exporter.ts
src/exporter/exporter.ts
src/exporter/local_exporter.ts
src/runner/circleci_runner.ts
src/runner/github_runner.ts
src/runner/jenkins_runner.ts

Collect and export test results. Currently, LocalExporter is only supported.
- GithubActions: Download zip artifact and extract then parse JUnit xml
- CircleCI: Parse test results that are provided from CircleCI API
- Jenkins: Download JUnit xml and parse it

Collect test results from CI services

---

src/analyzer/analyzer.ts
src/analyzer/circleci_analyzer.ts
src/analyzer/github_analyzer.ts
src/analyzer/jenkins_analyzer.ts
src/client/github_client.ts
src/client/jenkins_client.ts
src/config/circleci_config.ts
src/exporter/bigquery_exporter.ts
src/exporter/exporter.ts
src/exporter/local_exporter.ts
src/runner/circleci_runner.ts
src/runner/github_runner.ts
src/runner/jenkins_runner.ts
src/zip_extractor.ts

- Remove duplicate code
- Rename `report`to `workflowReport`
- Rename ArtifactExtractor to ZipExtractor

Refactor output test reports

---

bigquery_schema/test_report.json
src/analyzer/analyzer.ts
src/analyzer/circleci_analyzer.ts
src/analyzer/github_analyzer.ts
src/analyzer/jenkins_analyzer.ts
src/runner/circleci_runner.ts
src/runner/github_runner.ts
src/runner/jenkins_runner.ts

Add some columns to test_report table for creating a better test report dashboard.

Add test report schema

---

README.md
__tests__/analyzer/analyzer.test.ts
bigquery_schema/test_report.json
package-lock.json
package.json
src/analyzer/analyzer.ts
src/analyzer/circleci_analyzer.ts
src/analyzer/github_analyzer.ts
src/analyzer/jenkins_analyzer.ts

Add some columns for aggregating test success rate.
- testsuites.successCount
- testsuites.testsuite.testcase.successCount
Omit some columns that may contain huge free text.
- testsuites.testsuite.system-out
- testsuites.testsuite.system-err
- testsuites.testsuite.testcase.failure
- testsuites.testsuite.testcase.error
- testsuites.testsuite.testcase.system-out
- testsuites.testsuite.testcase.system-err

Fix test_rerport schema

---

src/client/circleci_client.ts
src/client/github_client.ts
src/client/jenkins_client.ts
src/exporter/bigquery_exporter.ts

Extends axios HTTP client timeout 1000ms to 3000ms.

Extends axios timeout

---

__tests__/analyzer/analyzer.test.ts
bigquery_schema/test_report.json
src/analyzer/analyzer.ts
src/exporter/bigquery_exporter.ts

More improve and bugfix from #35 
- Omit
- testsuite.properties
- testcase.skipped
- Add
- testcase.status

Fix BigQuery TestReport schema

---

__tests__/exporter/local_exporter.test.ts
src/exporter/local_exporter.ts

- Replace sync functions to async
- Add LocalExporter test

LocalExporter using async fs functions instead of sync.

---

Jenkinsfile
__tests__/config/jenkins_config.test.ts
__tests__/custom_report_collection.test.ts
src/analyzer/jenkins_analyzer.ts
src/client/jenkins_client.ts
src/config/config.ts
src/config/jenkins_config.ts
src/custom_report_collection.ts
src/exporter/bigquery_exporter.ts
src/exporter/exporter.ts
src/exporter/local_exporter.ts
src/runner/jenkins_runner.ts

Implement a feature collectiong custom format JSON and export to local file.
It only support Jenkins now.

feat: Collect custom JSON and export with local exporter(Jenkins)

---

.github/workflows/ci.yml
__tests__/config/github_config.test.ts
__tests__/config/jenkins_config.test.ts
src/analyzer/github_analyzer.ts
src/analyzer/jenkins_analyzer.ts
src/client/client.ts
src/client/github_client.ts
src/client/jenkins_client.ts
src/config/github_config.ts
src/runner/github_runner.ts

Collect CustomReport from Github Actions artifact and export to local and BigQuery are available by this pull-request.

feat: Export CustomReport (Github Actions)

---

.circleci/config.yml
__tests__/config/circleci_config.test.ts
__tests__/custom_report_collection.test.ts
src/analyzer/github_analyzer.ts
src/analyzer/jenkins_analyzer.ts
src/client/circleci_client.ts
src/config/circleci_config.ts
src/custom_report_collection.ts
src/runner/circleci_runner.ts
src/runner/github_runner.ts
src/runner/jenkins_runner.ts

Collect CustomReport from CircleCI artifact.

feat: Export CustomReport (CircleCI)

---

.github/workflows/ci.yml
.github/workflows/docker.yml
Dockerfile

- docker push to ghcr.io/kesin11/ci_analyzer:latest
- Replace `docker build` command to `docker/build-push-action@v2`

ci: docker push to Github Container Registry from Github Actions

---

ci_analyzer.yaml
src/client/jenkins_client.ts
src/config/jenkins_config.ts
src/runner/jenkins_runner.ts

Add `correctAllJobs` to Jenkins config.
It enables to correct pipeline workflow data from all jobs.

feat(Jenkins): Add correctAllJobs config

---

.github/workflows/docker.yml

ref:
- https://github.com/docker/build-push-action#handle-tags-and-labels
- https://github.com/crazy-max/ghaction-docker-meta#handle-semver-tag

ci: push semver docker tag to ghcr.io registroy

---

package-lock.json

Dependabot can't create fix pull-request, so I do `npm audit fix` manually.

fix: node-forge security vulnerability

---

__tests__/analyzer/bitrise_analyzer.test.ts
__tests__/config/bitrise_config.test.ts
__tests__/fixture/bitrise_build_log/failed.json
__tests__/fixture/bitrise_build_log/int_sec.json
src/analyzer/bitrise_analyzer.ts
src/client/bitrise_client.ts
src/config/bitrise_config.ts
src/config/config.ts
src/runner/bitrise_runner.ts
src/runner/runner.ts

Add to collect build data from Bitrise. 
Currently, it is experimental support and it can correct workflow data only.
I'm going to support correct test data and custom reports.

feat: Init Bitrise support

---

src/analyzer/analyzer.ts
src/analyzer/bitrise_analyzer.ts
src/analyzer/github_analyzer.ts
src/analyzer/jenkins_analyzer.ts
src/client/bitrise_client.ts
src/runner/bitrise_runner.ts

Support correcting JUnit test data in Bitrise.
Example config yaml:
```yaml
bitrise:
baseUrl: https://api.bitrise.io/v0.1 # default
apps:
- name: Kesin11/FlutterGettingStarted
tests:
- "*_test_results.xml"
```

Correct JUnit test data from Bitrise artifact

---

package-lock.json
package.json
src/config/config.ts

chore(deps): update js-yaml and migrate few code

---

src/client/github_client.ts
src/runner/github_runner.ts

Previously, Github Actions can not store each workflow's last run id, it stored only one workflow run number that is max number across all workflows.
This pull request fixes it, and each workflow last run ids are stored separately.

Bugfix storing last run id in Github Actions

---

Dockerfile
package-lock.json

- Update nodejs version inside Docker 12 to 14
- Update lockfileVersion 1 to 2 with npm v7

Update nodejs version and lockfileVersion

---

.dockerignore
Dockerfile

- Add unnecessary dirs to .dockerignore
- Don't include npm cache to runtime image

Little improve docker image size

---

README.md
__tests__/client/circleci_client.test.ts
__tests__/client/github_client.test.ts
__tests__/config/bitrise_config.test.ts
__tests__/config/circleci_config.test.ts
__tests__/config/github_config.test.ts
__tests__/config/jenkins_config.test.ts
__tests__/store/null_store.test.ts
src/arg_options.ts
src/client/bitrise_client.ts
src/client/circleci_client.ts
src/client/github_client.ts
src/config/bitrise_config.ts
src/config/circleci_config.ts
src/config/config.ts
src/config/github_config.ts
src/config/jenkins_config.ts
src/exporter/exporter.ts
src/index.ts
src/last_run_store.ts
src/runner/bitrise_runner.ts
src/runner/circleci_runner.ts
src/runner/github_runner.ts
src/runner/jenkins_runner.ts
src/runner/runner.ts
src/store/null_store.ts

Add some debug options. It helps us when to create or to update config YAML.
- --only-services
- --only-exporters
- --debug

Add debug options

---

__tests__/client/circleci_client.test.ts
__tests__/client/jenkins_client.test.ts
__tests__/exporter/bigquery_exporter.test.ts
__tests__/exporter/local_exporter.test.ts
__tests__/store/local_store.test.ts
__tests__/store/null_store.test.ts
package-lock.json
package.json
src/arg_options.ts
src/client/bitrise_client.ts
src/client/circleci_client.ts
src/client/client.ts
src/client/github_client.ts
src/client/jenkins_client.ts
src/config/config.ts
src/exporter/bigquery_exporter.ts
src/exporter/exporter.ts
src/exporter/local_exporter.ts
src/index.ts
src/last_run_store.ts
src/runner/bitrise_runner.ts
src/runner/circleci_runner.ts
src/runner/github_runner.ts
src/runner/jenkins_runner.ts
src/runner/runner.ts
src/store/gcs_store.ts
src/store/local_store.ts
src/store/null_store.ts

- Colorized logger
- Enable `-v` options. If shows debug level log.
- Silent logging in test

Improve logger

---

src/analyzer/circleci_analyzer.ts

CircleCI API v1.1 does not return workflow's status, so CircleCIAnalyzer detect workflow status from jobs that included it.
Previously only last build job status is used for detect workflow status, but it is incorrect when workflow has complex parallel jobs.
To fix it, workflow status is estimated using entire jobs instead of last one.

Fix detect workflow status in CircleCI

---

.github/workflows/ci.yml
.github/workflows/docker.yml
Earthfile
package.json

see: https://docs.earthly.dev/docs/guides/shared-cache

Use Earthly remote cache

---

README.md
bigquery_schema/workflow_report.json
proto/workflow.proto
src/analyzer/bitrise_analyzer.ts
src/analyzer/circleci_analyzer.ts
src/analyzer/circleci_analyzer_v2.ts
src/analyzer/github_analyzer.ts
src/analyzer/jenkins_analyzer.ts
src/client/bitrise_client.ts
src/pb_types/workflow.ts

Add commitMessage and actor to workflow schema.
`commitMessage` is a commit message of headSha.
`actor` is a commit author or trigger name provided by API.

Export commitMessage and actor data

---

README.md
bigquery_schema/workflow_report.json
proto/workflow.proto
src/analyzer/bitrise_analyzer.ts
src/analyzer/circleci_analyzer.ts
src/analyzer/circleci_analyzer_v2.ts
src/analyzer/github_analyzer.ts
src/analyzer/jenkins_analyzer.ts
src/pb_types/workflow.ts

Add some data of the job executor.
`executorClass` is a resource of the executor that relates performance.
`executorType` is a type of executor. (ex: docker or VM)
`executorName` is the name of the self-hosted executor.

Export job executor data

---

.circleci/config.yml
.github/workflows/docker.yml
Earthfile
package.json

see: https://docs.earthly.dev/docs/guides/shared-cache#explicit-cache-advanced

ci: More aggressive earthly explicit cache

---

src/client/circleci_client_v2.ts
src/client/client.ts
src/error.ts
src/index.ts
src/result.ts
src/runner/bitrise_runner.ts
src/runner/circleci_runner_v1.ts
src/runner/circleci_runner_v2.ts
src/runner/github_runner.ts
src/runner/jenkins_runner.ts
src/runner/runner.ts
tsconfig.json

- Show summarized axios error at global error handler
- Show nested stack trace at global error handler

Improve error log and stack trace

---

ci_analyzer.yaml
src/client/jenkins_client.ts
src/config/jenkins_config.ts
src/runner/jenkins_runner.ts

Resolve #617 
This is a feature addition proposal.
In order to reduce API calls, collect job name list with executing groovy script remotely.
Tentatively, I hardcode the groovy script so if you have any guideline to manage script resource, please let me know.
Thank you,
Takky

[Jenkins] Add new flag and logic to collect jobs

---

.github/workflows/ci.yml
.github/workflows/docker.yml

https://github.com/earthly/actions is moved https://github.com/earthly/actions-setup

ci: Use earthly/actions-setup

---

README.md

https://github.com/Kesin11/CIAnalyzer/pull/688 overwritten README by octocov's accidentally, so this PR restore CIAnalyzer README.

chore(docs): Restore CIAnalyzer README

---

package-lock.json
package.json
src/arg_options.ts
src/client/bitrise_client.ts
src/client/circleci_client.ts
src/client/circleci_client_v2.ts
src/client/client.ts
src/client/jenkins_client.ts
src/config/config.ts
src/exporter/bigquery_exporter.ts
src/exporter/exporter.ts
src/exporter/local_exporter.ts
src/index.ts
src/last_run_store.ts
src/runner/bitrise_runner.ts
src/runner/circleci_runner.ts
src/runner/circleci_runner_v1.ts
src/runner/circleci_runner_v2.ts
src/runner/github_runner.ts
src/runner/jenkins_runner.ts
src/runner/runner.ts
src/store/gcs_store.ts
src/store/local_store.ts
src/store/null_store.ts

close #666
tslog v4 has some BREAKING CHANGES for logging style.
I tried to maintain previous logging style as much as possible, but it has changed slightly.

Bump tslog 4.x and changed logging style slightly

---

package-lock.json
package.json
src/runner/runner.ts

Bump axios and remove redundant stacktrace log.

chore(deps): Bump axios to v1

---

.github/workflows/ci.yml
.github/workflows/docker.yml

ref: https://github.com/earthly/actions-setup/issues/14

ci: Fix earthly/actions-setup API limit exceeded error

---

package-lock.json
package.json
src/@types/axios-concurrency.ts
src/arg_options.ts
src/client/client.ts
tsconfig.json

fix: https://github.com/Kesin11/CIAnalyzer/issues/1036
> https://github.com/bernawil/axios-concurrency might be no longer maintenance.
For security reason, I want to remove axios-concurrency but preserve our max-concurrent-requests option.

Remove axios-concurrency

---

src/custom_report_collection.ts
src/exporter/exporter.ts
src/runner/runner.ts

see: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/

Refactor filter() type inference

---

src/client/github_client.ts

fix: https://github.com/Kesin11/CIAnalyzer/issues/1309

set per_page 100 for GitHub fetchJobs

---

renovate.json

zod updates are too frequent, so they will be changed to monthly.

Suppress renovate zod update

---

package-lock.json
package.json

Reverts Kesin11/CIAnalyzer#1471
Error log in my testing workflow. It seems to same issue #1438.
```
ERROR	[]
Error  Expected signal to be an instanceof AbortSignal, [object Object], , TypeError: Expected signal to be an instanceof AbortSignal
error stack:
• index.mjs	Gaxios._request
/ci_analyzer/dist/index.mjs:44464
• task_queues	process.processTicksAndRejections
internal/process/task_queues:105
• index.mjs	async IdentityPoolClient.requestAsync
/ci_analyzer/dist/index.mjs:47708
• index.mjs	async Upload.makeRequestStream
/ci_analyzer/dist/index.mjs:86958
• index.mjs	async Upload.startUploading
/ci_analyzer/dist/index.mjs:86797
ERROR	[]
Error  Expected signal to be an instanceof AbortSignal, [object Object], , TypeError: Expected signal to be an instanceof AbortSignal
error stack:
• …
```

Revert "chore(deps): update dependency @google-cloud/bigquery to v8"
